### PR TITLE
Reuse base configuration in kerberized HDP environments

### PR DESCRIPTION
**Pull request by wendigo**
Addresses https://github.com/prestosql/presto/issues/4097

### CODE REVIEW

**Comment by wendigo** [comment]
I've diffed original and overriding configuration to determine changes needed to be applied.

**Comment by wendigo** [comment]
@kokosing what you mean exactly?

**Comment by wendigo** [comment]
> Can you please rework the commits so each commit is split to:
> 
> * commit which moves files from conf to override
> * commit which removes extranous entries from files in override.
> 
> For sake of reviewability.
> 
> Sholuld not be much work

You will still need to compare files side by side to see a difference (properties interleave in a couple of files). I don't see how it will make this PR easier to comprehend (if you want to be 100% sure you will need to diff files yourself)

**Comment by kokosing** [comment]
> @kokosing what you mean exactly?

As I understand result files before your change and after change should logically have same content. And I was asking if you and how you verified this.

**Comment by wendigo** [comment]
@kokosing yes, I did

**Comment by losipiuk** [comment]
> You will still need to compare files side by side to see a difference (properties interleave in a couple of files). I don't see how it will make this PR easier to comprehend (if you want to be 100% sure you will need to diff files yourself)

It would be easier a bit. For single file would be rendered as changes. Not removal and addition. But to see of result did not change one would need to know what are the base files - and those are not part of the PR.

Given fact you did the validation yourself I am fine with the change mechanics.

**Comment by findepi** [comment]
Can we have the same for latest cdh env as well?

**Comment by wendigo** [comment]
@findepi yeah, I'm on it

**Comment by wendigo** [comment]
AC @findepi

**Comment by wendigo** [comment]
I'm attaching exported configuration files from final images:

[cdh5.12-hive-kerberized.tar.gz](https://github.com/prestosql/docker-images/files/4831297/cdh5.12-hive-kerberized.tar.gz)
[cdh5.15-hive-kerberized.tar.gz](https://github.com/prestosql/docker-images/files/4831298/cdh5.15-hive-kerberized.tar.gz)
[hdp2.6-hive-kerberized.tar.gz](https://github.com/prestosql/docker-images/files/4831299/hdp2.6-hive-kerberized.tar.gz)
[hdp3.1-hive-kerberized.tar.gz](https://github.com/prestosql/docker-images/files/4831300/hdp3.1-hive-kerberized.tar.gz)

**Comment by losipiuk** [comment]
Merged, thanks!

**Pull request merged**
