### PR TITLE
Make datenode not entering safe-mode on startup

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
@findepi should I apply this to HDP2.6 as well?

**Comment by wendigo** [comment]
Build failure is unreleated (ssl error on fetching https://cdn.azul.com/zulu/bin/zulu11.39.15-ca-jdk11.0.7-linux.x86_64.rpm)

**Comment by findepi** [comment]
> should I apply this to HDP2.6 as well?

idk what improvement it would be.
maybe not needed?

**Comment by findepi** [comment]
Merged, thanks!

**Pull request merged**
